project:
  type: book
  output-dir: docs

book:
  title: "Genehackers iGEM Wiki Guide"
  author: "Nipputi Thongthai"
  chapters:
    - index.qmd
    - repo-setup.qmd
    - react-tailwind.qmd
  page-navigation: true

format:
  html:
    theme: materia
